version: '3'
services:
  web:
    image: "ru.ifmo.kirmanak/elastic-app-manager:latest"
    ports:
      - "8080:8080"
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
  database:
    image: "postgres:12-alpine"
    env_file:
      - ./environment
